apiVersion: v1
kind: Namespace
metadata:
  name: kratix-platform-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: v1
kind: Namespace
metadata:
  name: platform-demo-system
