apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: todos-api
  annotations:
    platform.demoteam.io/base-url: http://todos-api.demo.svc.cluster.local:8080
spec:
  type: openapi
  lifecycle: production
  owner: group:default/platform
  definition:
    $text: ./todos.openapi.yaml
